# Generated by Django 5.1.5 on 2025-11-14 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('category', models.CharField(choices=[('burger', 'Burger'), ('pizza', 'Pizza'), ('sandwich', 'Sandwich & Specials'), ('plat', 'Plat'), ('tacos', 'Tacos'), ('desserts', 'Desserts'), ('drinks', 'Drinks')], max_length=50)),
                ('image', models.URLField(blank=True, null=True)),
                ('featured', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('delivery', 'Delivery'), ('dine_in', 'Dine In'), ('takeaway', 'Takeaway')], default='delivery', help_text='Type of order: delivery, dine_in, or takeaway', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='table_number',
            field=models.CharField(blank=True, help_text='Table number for dine-in orders', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(blank=True, help_text='Delivery address or table number for dine-in', max_length=255),
        ),
        migrations.CreateModel(
            name='MenuItemSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('M', 'Medium'), ('L', 'Large'), ('Mega', 'Mega')], max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='main.menuitem')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.menuitem')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.order')),
                ('size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.menuitemsize')),
            ],
        ),
    ]
