# Generated by Django 5.1.5 on 2025-11-14 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_menuitem_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_method',
        ),
    ]
