# Generated by Django 5.1.5 on 2025-11-15 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_ingredient_menuitemingredient'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItemSizeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=6)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.ingredient')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='main.menuitemsize')),
            ],
        ),
        migrations.DeleteModel(
            name='MenuItemIngredient',
        ),
    ]
