# Generated by Django 5.1.5 on 2025-11-15 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_menuitemsizeingredient_delete_menuitemingredient'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='reorder_level',
            field=models.DecimalField(decimal_places=2, default=10, help_text='Reorder level threshold', max_digits=10),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='stock',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Current stock quantity', max_digits=10),
        ),
    ]
