# Generated by Django 5.1.5 on 2025-11-15 19:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_ingredient_reorder_level_ingredient_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=0, help_text='Current stock quantity', max_digits=10)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('ingredient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock_record', to='main.ingredient')),
            ],
            options={
                'verbose_name': 'Ingredient Stock',
                'verbose_name_plural': 'Ingredient Stocks',
                'ordering': ['ingredient__name'],
            },
        ),
        migrations.CreateModel(
            name='IngredientTrace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_used', models.DecimalField(decimal_places=2, help_text='Quantity of ingredient used', max_digits=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('stock_before', models.DecimalField(blank=True, decimal_places=2, help_text='Stock quantity before this usage', max_digits=10, null=True)),
                ('stock_after', models.DecimalField(blank=True, decimal_places=2, help_text='Stock quantity after this usage', max_digits=10, null=True)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traces', to='main.ingredient')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_traces', to='main.order')),
                ('used_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingredient_usage_traces', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ingredient Trace',
                'verbose_name_plural': 'Ingredient Traces',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='main_ingred_timesta_8a6571_idx'), models.Index(fields=['ingredient', '-timestamp'], name='main_ingred_ingredi_79897c_idx')],
            },
        ),
    ]
