# Generated by Django 5.1.5 on 2025-11-16 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_add_menu_item_ingredient'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfflineOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, max_digits=15)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Preparing', 'Preparing'), ('Ready', 'Ready'), ('Served', 'Served'), ('Paid', 'Paid'), ('Canceled', 'Canceled')], default='Pending', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Special instructions or notes for the order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Offline Order',
                'verbose_name_plural': 'Offline Orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(help_text="Table number (e.g., '1', '2', 'VIP-1')", max_length=10, unique=True)),
                ('capacity', models.PositiveIntegerField(default=4, help_text='Maximum number of guests')),
                ('is_available', models.BooleanField(default=True, help_text='Whether the table is currently available')),
                ('location', models.CharField(blank=True, help_text="Table location (e.g., 'Window', 'Patio', 'Main Hall')", max_length=100)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the table')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Table',
                'verbose_name_plural': 'Tables',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='OfflineOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price at time of order', max_digits=10)),
                ('notes', models.CharField(blank=True, help_text='Special instructions for this item', max_length=255)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.menuitem')),
                ('offline_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='main.offlineorder')),
                ('size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.menuitemsize')),
            ],
            options={
                'verbose_name': 'Offline Order Item',
                'verbose_name_plural': 'Offline Order Items',
            },
        ),
        migrations.AddField(
            model_name='offlineorder',
            name='table',
            field=models.ForeignKey(help_text='Table number for this order', on_delete=django.db.models.deletion.CASCADE, related_name='offline_orders', to='main.table'),
        ),
    ]
