# Generated by Django 5.1.5 on 2025-11-16 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_offlineorder_table_offlineorderitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredienttrace',
            name='offline_order',
            field=models.ForeignKey(blank=True, help_text='Offline order that used this ingredient', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_traces', to='main.offlineorder'),
        ),
    ]
