# Generated by Django 5.1.5 on 2025-11-16 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_ingredienttrace_offline_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, help_text='Secure token for accessing this table', max_length=64, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this session is currently active')),
                ('expires_at', models.DateTimeField(help_text='When this session expires')),
                ('last_accessed', models.DateTimeField(auto_now=True, help_text='Last time this session was accessed')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the client accessing this session', null=True)),
                ('user_agent', models.CharField(blank=True, help_text='User agent of the client', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this session was created')),
                ('order_placed', models.BooleanField(default=False, help_text='Whether an order has been placed in this session')),
                ('table', models.ForeignKey(help_text='Table this session is for', on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='main.table')),
            ],
            options={
                'verbose_name': 'Table Session',
                'verbose_name_plural': 'Table Sessions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['token'], name='main_tables_token_3ef2e5_idx'), models.Index(fields=['table', 'is_active'], name='main_tables_table_i_ec9be4_idx'), models.Index(fields=['expires_at'], name='main_tables_expires_812d45_idx')],
            },
        ),
    ]
