# Generated by Django 5.1.5 on 2025-11-16 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_tablesession'),
    ]

    operations = [
        migrations.AddField(
            model_name='offlineorder',
            name='is_confirmed_cashier',
            field=models.BooleanField(default=False, help_text='Whether the cashier has confirmed this order'),
        ),
        migrations.AddField(
            model_name='order',
            name='is_confirmed_cashier',
            field=models.BooleanField(default=False, help_text='Whether the cashier has confirmed this order'),
        ),
    ]
