# Generated by Django 5.1.5 on 2025-11-18 08:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_offlineorder_is_confirmed_cashier_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, choices=[('admin', 'Admin'), ('cashier', 'Cashier'), ('chef', 'Chef')], help_text='Role to notify (null for all roles)', max_length=20, null=True)),
                ('notification_type', models.CharField(choices=[('order', 'Order'), ('alert', 'Alert'), ('info', 'Info'), ('ingredient', 'Ingredient'), ('table', 'Table')], default='info', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_ingredient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='main.ingredient')),
                ('related_offline_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='main.offlineorder')),
                ('related_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='main.order')),
                ('user', models.ForeignKey(blank=True, help_text='Specific user to notify (null for all users or role-based)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='main_notifi_user_id_4211ba_idx'), models.Index(fields=['role', '-created_at'], name='main_notifi_role_b27906_idx'), models.Index(fields=['is_read', '-created_at'], name='main_notifi_is_read_5ab903_idx')],
            },
        ),
    ]
