# Generated by Django 5.1.5 on 2025-11-18 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='priority',
            field=models.CharField(choices=[('critical', 'Critical'), ('medium', 'Medium'), ('low', 'Low')], default='medium', help_text='Notification priority: critical (sound+real-time), medium (real-time only), low (daily digest)', max_length=20),
        ),
    ]
