# Generated by Django 5.1.5 on 2025-12-20 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_alter_menuitem_image_alter_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Cost price for profit calculation', max_digits=6),
        ),
        migrations.AddField(
            model_name='menuitemsize',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Cost price for profit calculation', max_digits=6),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='menu_items/'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Selling price', max_digits=6),
        ),
        migrations.AlterField(
            model_name='menuitemsize',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Selling price', max_digits=6),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
    ]
