# Generated by Django 5.1.5 on 2025-12-20 15:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_menuitem_cost_price_menuitemsize_cost_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Supplier name', max_length=200)),
                ('phone', models.CharField(help_text='Supplier phone number', max_length=20)),
                ('supplier_type', models.CharField(choices=[('food', 'Food'), ('beverage', 'Beverage'), ('equipment', 'Equipment'), ('other', 'Other')], default='food', help_text='Type of supplier', max_length=50)),
                ('debt', models.DecimalField(decimal_places=2, default=0.0, help_text='Current debt amount owed to supplier', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Supplier',
                'verbose_name_plural': 'Suppliers',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='ingredient',
            name='supplier',
            field=models.ForeignKey(blank=True, help_text='Primary supplier for this ingredient', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingredients', to='main.supplier'),
        ),
        migrations.CreateModel(
            name='SupplierHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('purchase', 'Purchase'), ('payment', 'Payment'), ('adjustment', 'Adjustment'), ('refund', 'Refund')], help_text='Type of transaction', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Transaction amount (positive for purchases/debt, negative for payments)', max_digits=10)),
                ('description', models.TextField(blank=True, help_text='Description or notes about the transaction')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this transaction', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_transactions', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(help_text='Supplier associated with this transaction', on_delete=django.db.models.deletion.CASCADE, related_name='history', to='main.supplier')),
            ],
            options={
                'verbose_name': 'Supplier History',
                'verbose_name_plural': 'Supplier Histories',
                'ordering': ['-created_at'],
            },
        ),
    ]
