# Generated by Django 5.1.5 on 2025-12-20 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_supplier_ingredient_supplier_supplierhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='supplier_type',
            field=models.CharField(blank=True, help_text='Type of supplier', max_length=50),
        ),
    ]
