# Generated by Django 5.1.5 on 2025-12-20 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_alter_supplier_supplier_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierhistory',
            name='transaction_type',
            field=models.CharField(choices=[('purchase', 'Purchase'), ('payment', 'Payment')], help_text='Type of transaction', max_length=20),
        ),
    ]
