# Generated by Django 5.1.5 on 2025-12-20 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_alter_supplierhistory_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Cost per unit', max_digits=10),
        ),
    ]
