# Generated by Django 5.1.5 on 2025-12-20 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_ingredient_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierTransactionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Quantity purchased', max_digits=10)),
                ('price_per_unit', models.DecimalField(decimal_places=2, help_text='Price per unit at the time of purchase', max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, help_text='Total price for this item (quantity * price_per_unit)', max_digits=10)),
                ('ingredient', models.ForeignKey(help_text='The ingredient purchased', on_delete=django.db.models.deletion.CASCADE, related_name='transaction_items', to='main.ingredient')),
                ('supplier_history', models.ForeignKey(help_text='The parent transaction', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='main.supplierhistory')),
            ],
            options={
                'verbose_name': 'Supplier Transaction Item',
                'verbose_name_plural': 'Supplier Transaction Items',
            },
        ),
    ]
