# Generated by Django 5.1.5 on 2025-12-20 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_suppliertransactionitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientFidele',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Customer name', max_length=100)),
                ('phone', models.CharField(help_text='Customer phone number', max_length=20, unique=True)),
                ('loyalty_card_number', models.CharField(blank=True, help_text='Unique loyalty card number (auto-generated if empty)', max_length=20, unique=True)),
                ('points', models.IntegerField(default=0, help_text='Loyalty points earned')),
                ('total_spent', models.DecimalField(decimal_places=2, default=0.0, help_text='Total amount spent by this customer', max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Loyal Customer',
                'verbose_name_plural': 'Loyal Customers',
                'ordering': ['-created_at'],
            },
        ),
    ]
