# Generated by Django 5.1.5 on 2025-12-20 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_clientfidele'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientfidele',
            name='points',
        ),
    ]
