# Generated by Django 5.1.5 on 2025-12-20 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_remove_clientfidele_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='loyal_customer',
            field=models.ForeignKey(blank=True, help_text='Loyal customer if applicable', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='main.clientfidele'),
        ),
        migrations.AddField(
            model_name='order',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes or special instructions for the order'),
        ),
    ]
