# Generated by Django 5.1.5 on 2025-12-20 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_order_loyal_customer_order_notes'),
    ]

    operations = [
        # First, update all existing NULL values to empty string
        migrations.RunSQL(
            sql="UPDATE main_order SET notes = '' WHERE notes IS NULL;",
            reverse_sql="UPDATE main_order SET notes = NULL WHERE notes = '';",
        ),
        # Then alter the field to add default
        migrations.AlterField(
            model_name='order',
            name='notes',
            field=models.TextField(blank=True, default='', help_text='Additional notes or special instructions for the order'),
        ),
    ]
