# Generated by Django 5.1.5 on 2025-12-21 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_add_notes_default'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='supplier',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='suppliers',
            field=models.ManyToManyField(blank=True, help_text='Suppliers who provide this ingredient', related_name='ingredients', to='main.supplier'),
        ),
    ]
