# Generated by Django 5.1.5 on 2025-12-21 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_remove_ingredient_supplier_ingredient_suppliers'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='loyalty_number',
            field=models.CharField(blank=True, help_text='Loyalty card number entered by the customer', max_length=20, null=True),
        ),
    ]
