# Generated by Django 5.1.5 on 2025-12-21 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_order_subtotal_order_tax_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='offlineorder',
            name='revenue',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Revenue calculated as sell price - cost price (no tax)', max_digits=15),
        ),
        migrations.AddField(
            model_name='order',
            name='revenue',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Revenue calculated as sell price - cost price (no tax)', max_digits=15),
        ),
        migrations.AlterField(
            model_name='offlineorder',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed')], default='Pending', max_length=20),
        ),
    ]
