# Generated by Django 5.1.5 on 2025-12-21 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='ingredient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waste_expenses', to='main.ingredient'),
        ),
        migrations.AddField(
            model_name='expense',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Quantity of ingredient wasted', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='ingredienttrace',
            name='notes',
            field=models.TextField(blank=True, help_text='Notes about the usage', null=True),
        ),
    ]
