# Generated by Django 5.1.5 on 2025-12-21 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_staffmember'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='staff_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='main.staffmember'),
        ),
    ]
