# Generated by Django 5.1.5 on 2025-12-21 23:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_promotion_promotionitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='description',
            field=models.TextField(blank=True, help_text='Short teaser for the promotion banner'),
        ),
        migrations.AddField(
            model_name='promotionitem',
            name='menu_item_size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.menuitemsize'),
        ),
    ]
