# Generated by Django 5.1.5 on 2025-12-22 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_promotion_description_promotionitem_menu_item_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='applicable_sizes',
            field=models.ManyToManyField(blank=True, related_name='promotions', to='main.menuitemsize'),
        ),
    ]
