# Generated by Django 5.1.5 on 2025-12-22 00:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_promotion_applicable_sizes'),
    ]

    operations = [
        migrations.AddField(
            model_name='offlineorder',
            name='is_imported',
            field=models.BooleanField(default=False, help_text='Whether this order was imported from an external source'),
        ),
        migrations.AlterField(
            model_name='offlineorder',
            name='table',
            field=models.ForeignKey(blank=True, help_text='Table number for this order', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offline_orders', to='main.table'),
        ),
    ]
