# Generated by Django 5.1.5 on 2026-02-03 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0044_alter_offlineorder_status_alter_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening_time', models.TimeField(help_text='Restaurant opening time')),
                ('closing_time', models.TimeField(help_text='Restaurant closing time')),
            ],
            options={
                'verbose_name': 'Restaurant Info',
                'verbose_name_plural': 'Restaurant Info',
            },
        ),
        migrations.AlterField(
            model_name='menuitemsize',
            name='size',
            field=models.CharField(choices=[('XS', 'Extra Small'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large'), ('Mega', 'Mega'), ('Family', 'Family')], max_length=10),
        ),
        migrations.AlterField(
            model_name='offlineorder',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
    ]
