# Generated by Django 5.1.5 on 2026-02-06 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0045_restaurantinfo_alter_menuitemsize_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
