# Generated by Django 5.1.5 on 2026-02-06 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0046_alter_menuitem_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staffmember',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
