# Generated by Django 5.1.5 on 2026-02-26 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0047_alter_profile_image_alter_staffmember_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItemExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, help_text='Additional selling price for this extra', max_digits=6)),
                ('cost_price', models.DecimalField(decimal_places=2, default=0.0, help_text='Cost price for this extra (for profit calculation)', max_digits=6)),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extras', to='main.menuitem')),
            ],
            options={
                'verbose_name': 'Menu Item Extra',
                'verbose_name_plural': 'Menu Item Extras',
            },
        ),
    ]
