# Generated by Django 5.1.5 on 2026-02-27 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0048_menuitemextra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='category',
            field=models.CharField(choices=[('burger', 'Burger'), ('pizza', 'Pizza'), ('sandwich', 'Sandwich & Specials'), ('plat', 'Plat'), ('tacos', 'Tacos'), ('desserts', 'Desserts'), ('drinks', 'Drinks'), ('cafeteria', 'Cafeteria'), ('crepes', 'Crepes')], max_length=50),
        ),
    ]
