# Generated by Django 5.1.5 on 2026-03-05 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0049_alter_menuitem_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='offlineorderitem',
            name='extras',
            field=models.JSONField(blank=True, default=list, help_text='Selected paid extras (id, name, price)', null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='extras',
            field=models.JSONField(blank=True, default=list, help_text='Selected paid extras (id, name, price)', null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='category',
            field=models.CharField(choices=[('burger', 'Burger'), ('pizza', 'Pizza'), ('sandwich', 'Sandwich & Specials'), ('plat', 'Plat'), ('tacos', 'Tacos'), ('desserts', 'Desserts'), ('drinks', 'Drinks'), ('cafétéria', 'Cafétéria'), ('crêpes', 'Crêpes'), ('entrées', 'Entrées')], max_length=50),
        ),
    ]
